### ISSUE TITLE
MediatR library

### ISSUE THREAD

**Issue by ricksecretin** [vkhorikov/CqrsInPractice#10]
Hey,

Your course on this was really great!

In the introduction of the course you mention that you will introduce the open source library MediatR. Later on you implement your own 'mediator'. 
Is there any reason why you prefer your own implementation over MediatR?

Thanks in advance.

**Comment by vkhorikov** [comment]
I had to cut the material about MediatR because the course was too lengthy already. I plan to do a separate course on this topic.
