### ISSUE TITLE
Exposing `AuditLoggingDecorator` implementation details in class name

### ISSUE THREAD

**Issue by sshushliapin** [vkhorikov/CqrsInPractice#11]
Hi @vkhorikov! I'm a big fan of your PS courses abd blogposts. I often use the course repos as reference when designing my API. Great job, keep doint it!

There is one things that bothers me in this particular repo. Why does [`AuditLoggingDecorator`](https://github.com/vkhorikov/CqrsInPractice/blob/master/After/src/Logic/Decorators/AuditLoggingDecorator.cs#L8) (or `DatabaseRetryDecorator`) expose its structure and implementatin details in the class name? The purpose of the first class is to introduce logging behavior. That's it. Looking on the class name, why should I care if it's a decorator or not? Nothing should prevent me from refactoring the class and replacing decorator with, let's say, inheritense from some base class or even copy-pasting from other source (!). Of course, composition is preferable, but why should it go to the class name? Will I have to rename it to `AuditLoggingInheritedFromBase` or `AuditLoggingCopyPaste` in case of not using Decorator pattern? Sounds awkward, isn't it?

Wouldn't it be better to have a class called `AuditLoggingCommandHandler`? This name provides clear understanding of the class _purpose_ and is resistant to inner implementation changes. Any thoughts regarding this?

**Comment by vkhorikov** [comment]
Yeah, it's a good question. This is a somewhat ongoing debate. The same arguments can be applied to `UserRepository` ("why does it have the word `Repository` in it") or `UserFactory`, or command handlers, for that matter.

The line between names that improve readability and names that just expose internal implementation details is blurry. I would say that there are 2 types of patterns: those that describe implementation details only and those that also show the intent. The latter are useful for people to know when they read the class, and so it helps understand the code when they see the pattern in the class name. I think both Factory, Repository, and Decorator fall into the latter category.

But that's only when you work in the application layer. The domain layer should be written using the ubiquitous language only ( https://enterprisecraftsmanship.com/posts/ubiquitous-language-naming/ ).

> Wouldn't it be better to have a class called AuditLoggingCommandHandler? This name provides clear understanding of the class purpose and is resistant to inner implementation changes. Any thoughts regarding this?

The purpose of the handler is not to audit or log, those are just side non-functional details, so I don't think putting these names in the command handler is helpful.

**Comment by sshushliapin** [comment]
Thanks, @vkhorikov.

> it helps understand the code when they see the pattern in the class name. I think both Factory, Repository, and Decorator fall into the latter category.

For me, Factory or Repository names bring clear purpose - to compose objects and to take care about storage. I do welcome these names. I cannot say the same about Decorator... There is no such a purpose as 'to decorate'. We can augment the class functionality _via_ decorating, but the decorating itself is not the goal...

> The purpose of the handler is not to audit or log, those are just side non-functional details

Sorry, did not get this... How can it be that the purpose of class with 'Logging' in name and logging functionality inside is not logging? Or you're talking about command handlers in general?

**Comment by vkhorikov** [comment]
> For me, Factory or Repository names bring clear purpose - to compose objects and to take care about storage. I do welcome these names. I cannot say the same about Decorator...

This could be due to sheer familiarity. I don't see significant difference between the Factory and Decorator patterns in terms of their descriptiveness.

> How can it be that the purpose of class with 'Logging' in name and logging functionality inside is not logging? Or you're talking about command handlers in general?

The purpose of a command handler is to handle one of the application's use cases, for example edit a user's personal info (`EditPersonalInfoCommandHandler`). Logging or retrying is a cross-cutting concern which is not the primary goal of the command handler, so it shouldn't be in its name.

**Comment by sshushliapin** [comment]
> This could be due to sheer familiarity

funny :-D

> a cross-cutting concern which is not the primary goal of the command handler, so it shouldn't be in its name

Interesting... I have never thought about naming from this point of view... Good point!

Thanks for your ansvers, @vkhorikov!
