### ISSUE TITLE
HTTP Status Codes For Command Failures

### ISSUE THREAD

**Issue by codyspeck** [vkhorikov/CqrsInPractice#5]
Hi Vladimir.

This isn't a technical issue with this repository so much as it is a question for you.

Using a CQRS approach like this repository does, do you have any recommendations on how one would go about responding with different http status codes depending on the nature of a command's failure without API (UI) logic leaking into the application services layer?

Example:

In your StudentController (https://github.com/vkhorikov/CqrsInPractice/blob/master/After/src/Api/Controllers/StudentController.cs) the following method takes in a Student's ID and a StudentEnrollmentDto:

```C#
[HttpPost("{id}/enrollments")]
public IActionResult Enroll(long id, [FromBody] StudentEnrollmentDto dto)
{
    Result result = _messages.Dispatch(new EnrollCommand(id, dto.Course, dto.Grade));
    return FromResult(result);
}
```

What might we do if we wanted to respond with a 404 error if no matching Student is found with the provided ID, but respond with a generic 400 if some other expected failure occurs in the EnrollCommand handler?

**Comment by vkhorikov** [comment]
I recommend the following:

1) Create a custom `Error` value object. List application errors explicitly in one place, like:

```
class Errors {
  class General {
    public static Error NotFound(string entityName, long id) {
      return new Error("error.code.goes.here", /* compose a nice error message here */); }
    /* other errors */
  }
}
```

2. Use the `Result<T,E>` version of `Result` or introduce your own `Result` specific to your app that would use `Error` as `E`

3. In `BaseController`, modify `FromResult` to distinguish between different types of errors.

**Comment by codyspeck** [comment]
Got it. Thanks for taking the time to share some advice!
