### ISSUE TITLE
[Q] DTOs and Onion Architecture

### ISSUE THREAD

**Issue by dehghani-mehdi** [vkhorikov/CqrsInPractice#6]
Hi,

I just saw your course, great job.

As you mentioned in `The Read Model and the Onion Architecture`, the DTOs belongs to outer later of Onion Architecture, the UI layer, but [Microsoft believes DTOs belongs to core layer](https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/common-web-application-architectures#organizing-code-in-clean-architecture). so which one is correct and why?

Thank you!

**Comment by vkhorikov** [comment]
Don't know why they included it into the application core, could be a mistake, but DTOs should definitely not belong to that layer. The core layer is for the core domain logic. DTOs come from external applications and must be translated into domain objects by app services.

**Comment by dehghani-mehdi** [comment]
[Steve Smith](https://github.com/ardalis), another Pluralsight teacher, also [included DTOs into the core layer](https://github.com/ardalis/CleanArchitecture#the-core-project).

> DTOs come from external applications

What do you mean by "external applications"?

**Comment by vkhorikov** [comment]
I recommend module "Decoupling the Domain Model from Data Contracts" of my other course "Refactoring from Anemic Domain Model Towards a Rich One" for the reasons why you need to separate DTOs from the domain layer.

**Comment by dehghani-mehdi** [comment]
Okay, thank you for your time, I'll try to watch that.
